# Generated by Django 2.2.5 on 2019-09-20 12:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='staff_detail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=None, max_length=200)),
                ('gender', models.CharField(max_length=200, null=True)),
                ('dob', models.DateField(default=None)),
                ('fath_hus_name', models.CharField(default=None, max_length=200)),
                ('official_mail', models.EmailField(help_text='A valid email address, please.', max_length=254, null=True)),
                ('personal_mail', models.EmailField(help_text='A valid email address, please.', max_length=254, null=True)),
                ('aadhar', models.IntegerField(default=None)),
                ('pan', models.IntegerField(default=None)),
                ('mobile_no', models.IntegerField(default=None)),
                ('residence_ph_no', models.IntegerField(default=None)),
                ('caste', models.CharField(max_length=200, null=True)),
                ('community', models.CharField(max_length=200, null=True)),
                ('res_address', models.CharField(max_length=1000, null=True)),
                ('perm_address', models.CharField(max_length=1000, null=True)),
                ('website_url', models.URLField(default=None, max_length=250)),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Staff',
            },
        ),
        migrations.CreateModel(
            name='qualification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(default=None, max_length=200, null=True)),
                ('degree', models.CharField(max_length=200)),
                ('branch', models.CharField(default=None, max_length=200, null=True)),
                ('institution', models.CharField(max_length=400)),
                ('university', models.CharField(max_length=400)),
                ('duration', models.CharField(max_length=300)),
                ('class_obtained', models.CharField(default=None, max_length=200, null=True)),
                ('title_of_thesis', models.CharField(default=None, max_length=700, null=True)),
                ('research_area', models.CharField(default=None, max_length=300, null=True)),
                ('faculty', models.CharField(default=None, max_length=200, null=True)),
                ('department', models.CharField(default=None, max_length=200, null=True)),
                ('viva', models.CharField(default=None, max_length=100, null=True)),
                ('degree_type', models.CharField(default=None, max_length=200)),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Qualifications',
            },
        ),
        migrations.CreateModel(
            name='publication',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=800)),
                ('level', models.CharField(max_length=400)),
                ('year', models.IntegerField()),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Publications',
            },
        ),
        migrations.CreateModel(
            name='project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pro_title', models.CharField(max_length=800)),
                ('funding_agent', models.CharField(max_length=400)),
                ('amt', models.IntegerField()),
                ('pro_type', models.CharField(max_length=400)),
                ('staff', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Projects',
            },
        ),
        migrations.CreateModel(
            name='employment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('designation', models.CharField(max_length=400)),
                ('from_date', models.DateField()),
                ('department', models.CharField(default=None, max_length=400)),
                ('campus', models.CharField(default=None, max_length=400)),
                ('present_pay', models.IntegerField(default=None)),
                ('nature_of_app', models.CharField(default=None, max_length=400)),
                ('position', models.CharField(default=None, max_length=400)),
                ('position_type', models.CharField(default=None, max_length=400)),
                ('institution', models.CharField(default=None, max_length=400)),
                ('years', models.CharField(default=None, max_length=400)),
                ('exp_type', models.CharField(default=None, max_length=400)),
                ('emp_type', models.CharField(default=None, max_length=200)),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Employment details',
            },
        ),
        migrations.CreateModel(
            name='csw',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=800)),
                ('type_name', models.CharField(max_length=400)),
                ('level', models.CharField(max_length=400)),
                ('csw_type', models.CharField(max_length=400)),
                ('staff', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Conference/Seminar/Workshop',
            },
        ),
        migrations.CreateModel(
            name='area_of_spec_and_mem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area_name', models.CharField(default=None, max_length=500, null=True)),
                ('mem', models.CharField(default=None, max_length=500, null=True)),
                ('spec_mem_type', models.CharField(max_length=200)),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Specializations and Membership',
            },
        ),
    ]
