# Generated by Django 2.2.5 on 2019-09-20 12:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='csw',
            name='staff',
        ),
        migrations.RemoveField(
            model_name='employment',
            name='staff',
        ),
        migrations.RemoveField(
            model_name='project',
            name='staff',
        ),
        migrations.RemoveField(
            model_name='publication',
            name='staff',
        ),
        migrations.RemoveField(
            model_name='qualification',
            name='staff',
        ),
        migrations.RemoveField(
            model_name='staff_detail',
            name='user',
        ),
        migrations.DeleteModel(
            name='area_of_spec_and_mem',
        ),
        migrations.DeleteModel(
            name='csw',
        ),
        migrations.DeleteModel(
            name='employment',
        ),
        migrations.DeleteModel(
            name='project',
        ),
        migrations.DeleteModel(
            name='publication',
        ),
        migrations.DeleteModel(
            name='qualification',
        ),
    ]
