# Generated by Django 2.2.5 on 2019-09-21 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0003_auto_20190921_1324'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff_detail',
            name='dob',
            field=models.DateField(default=None),
        ),
    ]
