# Generated by Django 2.2.5 on 2019-09-21 07:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0004_staff_detail_dob'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='staff_detail',
            name='dob',
        ),
    ]
