# Generated by Django 2.2.5 on 2019-09-21 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0005_remove_staff_detail_dob'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff_detail',
            name='dob',
            field=models.DateField(default=None),
        ),
    ]
