# Generated by Django 2.2.5 on 2019-09-21 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0007_auto_20190921_1349'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff_detail',
            name='caste',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='staff_detail',
            name='community',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='staff_detail',
            name='mobile_no',
            field=models.IntegerField(default=None),
        ),
        migrations.AddField(
            model_name='staff_detail',
            name='perm_address',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='staff_detail',
            name='res_address',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='staff_detail',
            name='residence_ph_no',
            field=models.IntegerField(default=None),
        ),
    ]
