# Generated by Django 2.2.5 on 2019-09-21 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0008_auto_20190921_1353'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff_detail',
            name='website_url',
            field=models.URLField(default=None, max_length=250),
        ),
    ]
