# Generated by Django 2.2.5 on 2019-09-25 21:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0011_auto_20190922_1032'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='staff_detail',
            name='dob',
        ),
    ]
