# Generated by Django 2.2.5 on 2019-09-25 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0015_auto_20190926_0313'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff_detail',
            name='aadhar',
            field=models.IntegerField(default=None),
        ),
        migrations.AddField(
            model_name='staff_detail',
            name='caste',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='staff_detail',
            name='community',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='staff_detail',
            name='dob',
            field=models.DateField(default=None),
        ),
        migrations.AddField(
            model_name='staff_detail',
            name='fath_hus_name',
            field=models.CharField(default=None, max_length=200),
        ),
        migrations.AddField(
            model_name='staff_detail',
            name='gender',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='staff_detail',
            name='mobile_no',
            field=models.IntegerField(default=None),
        ),
        migrations.AddField(
            model_name='staff_detail',
            name='official_mail',
            field=models.EmailField(help_text='A valid email address, please.', max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='staff_detail',
            name='pan',
            field=models.IntegerField(default=None),
        ),
        migrations.AddField(
            model_name='staff_detail',
            name='perm_address',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='staff_detail',
            name='personal_mail',
            field=models.EmailField(help_text='A valid email address, please.', max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='staff_detail',
            name='res_address',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='staff_detail',
            name='residence_ph_no',
            field=models.IntegerField(default=None),
        ),
        migrations.AddField(
            model_name='staff_detail',
            name='website_url',
            field=models.URLField(default=None, max_length=250),
        ),
    ]
