# Generated by Django 2.2.5 on 2019-09-25 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0017_remove_staff_detail_dob'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff_detail',
            name='dob',
            field=models.DateField(default=None),
        ),
        migrations.AlterField(
            model_name='staff_detail',
            name='website_url',
            field=models.URLField(default=None, max_length=1000),
        ),
    ]
