# Generated by Django 2.2.6 on 2019-11-19 06:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('staff', '0018_auto_20190926_0327'),
    ]

    operations = [
        migrations.CreateModel(
            name='qualification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(default=None, max_length=200, null=True)),
                ('degree', models.CharField(max_length=200)),
                ('branch', models.CharField(default=None, max_length=200, null=True)),
                ('institution', models.CharField(max_length=400)),
                ('university', models.CharField(max_length=400)),
                ('duration', models.CharField(max_length=300)),
                ('class_obtained', models.CharField(default=None, max_length=200, null=True)),
                ('title_of_thesis', models.CharField(default=None, max_length=700, null=True)),
                ('research_area', models.CharField(default=None, max_length=300, null=True)),
                ('faculty', models.CharField(default=None, max_length=200, null=True)),
                ('department', models.CharField(default=None, max_length=200, null=True)),
                ('viva', models.CharField(default=None, max_length=100, null=True)),
                ('degree_type', models.CharField(default=None, max_length=200)),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Qualifications',
            },
        ),
    ]
