# Generated by Django 2.2.6 on 2019-11-19 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0022_auto_20191119_1617'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qualification',
            name='degree',
            field=models.CharField(default=None, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='qualification',
            name='duration',
            field=models.CharField(default=None, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='qualification',
            name='institution',
            field=models.CharField(default=None, max_length=400, null=True),
        ),
        migrations.AlterField(
            model_name='qualification',
            name='university',
            field=models.CharField(default=None, max_length=400, null=True),
        ),
    ]
