# Generated by Django 2.2.6 on 2019-11-19 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0023_auto_20191119_1630'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qualification',
            name='degree',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='qualification',
            name='duration',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='qualification',
            name='institution',
            field=models.CharField(max_length=400),
        ),
        migrations.AlterField(
            model_name='qualification',
            name='university',
            field=models.CharField(max_length=400),
        ),
    ]
