# Generated by Django 2.2.6 on 2019-11-20 08:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('staff', '0029_auto_20191119_1726'),
    ]

    operations = [
        migrations.CreateModel(
            name='area_of_spec_and_mem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area_name', models.CharField(default=None, max_length=500, null=True)),
                ('mem', models.CharField(default=None, max_length=500, null=True)),
                ('spec_mem_type', models.CharField(max_length=200)),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Specializations and Membership',
            },
        ),
    ]
