# Generated by Django 2.2.6 on 2019-11-20 08:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0030_area_of_spec_and_mem'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='area_of_spec_and_mem',
            options={'verbose_name_plural': 'Specialization and Membership'},
        ),
    ]
