# Generated by Django 2.2.6 on 2019-11-20 08:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0031_auto_20191120_1408'),
    ]

    operations = [
        migrations.AlterField(
            model_name='area_of_spec_and_mem',
            name='staff',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='area_of_spec_and_mem', to=settings.AUTH_USER_MODEL),
        ),
    ]
