# Generated by Django 2.2.6 on 2019-11-20 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0033_employment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employment',
            name='position_type',
            field=models.CharField(default=None, max_length=400, null=True),
        ),
    ]
