# Generated by Django 2.2.6 on 2019-11-20 14:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0034_auto_20191120_1923'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employment',
            name='to_date',
        ),
        migrations.AlterField(
            model_name='employment',
            name='designation',
            field=models.CharField(max_length=400, null=True),
        ),
        migrations.AlterField(
            model_name='employment',
            name='staff',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
