# Generated by Django 2.2.6 on 2019-11-23 17:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('staff', '0037_publication'),
    ]

    operations = [
        migrations.CreateModel(
            name='csw',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default=None, max_length=800)),
                ('type_name', models.CharField(default=None, max_length=400)),
                ('level', models.CharField(default=None, max_length=400, null=True)),
                ('country', models.CharField(default=None, max_length=400, null=True)),
                ('csw_type', models.CharField(max_length=400)),
                ('staff', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Conference/Seminar/Workshop',
            },
        ),
    ]
