# Generated by Django 2.2.6 on 2019-11-23 18:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('staff', '0038_csw'),
    ]

    operations = [
        migrations.AlterField(
            model_name='csw',
            name='staff',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='csw', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pro_title', models.CharField(default=None, max_length=800)),
                ('funding_agent', models.CharField(default=None, max_length=400)),
                ('amt', models.IntegerField(default=None)),
                ('pro_type', models.CharField(default=None, max_length=800)),
                ('staff', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='project', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Projects',
            },
        ),
    ]
