# Generated by Django 2.2.6 on 2019-11-23 19:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('staff', '0039_auto_20191123_2341'),
    ]

    operations = [
        migrations.CreateModel(
            name='invited_lectures',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(default=None, max_length=400)),
                ('topic', models.CharField(default=None, max_length=400)),
                ('programme', models.CharField(default=None, max_length=400)),
                ('instituion', models.CharField(default=None, max_length=800)),
                ('place', models.CharField(default=None, max_length=400)),
                ('date', models.DateField(default=None)),
                ('staff', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='invited_lectures', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Invited Lectures',
            },
        ),
        migrations.CreateModel(
            name='ext_and_outreach_prog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_of_prog', models.CharField(default=None, max_length=400)),
                ('title_of_prog', models.CharField(default=None, max_length=400)),
                ('your_role', models.CharField(default=None, max_length=400, null=True)),
                ('cross_sec_of_participants', models.CharField(default=None, max_length=800, null=True)),
                ('no_of_participants', models.CharField(default=None, max_length=400)),
                ('funded_by', models.CharField(default=None, max_length=400)),
                ('venue', models.CharField(default=None, max_length=400)),
                ('from_date', models.DateField(default=None)),
                ('to_date', models.DateField(default=None)),
                ('staff', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ext_and_outreach_programme', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Extension and Outreach Programmes',
            },
        ),
        migrations.CreateModel(
            name='experience_abroad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nature_of_assignment', models.CharField(default=None, max_length=400)),
                ('from_date', models.DateField(default=None)),
                ('to_date', models.DateField(default=None)),
                ('instituion', models.CharField(default=None, max_length=800)),
                ('country', models.CharField(default=None, max_length=400)),
                ('purp_of_visit', models.CharField(default=None, max_length=400)),
                ('funding_agency', models.CharField(default=None, max_length=400)),
                ('staff', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='experience_abroad', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Experience(Abroad)',
            },
        ),
        migrations.CreateModel(
            name='book_published',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default=None, max_length=400)),
                ('author', models.CharField(default=None, max_length=400)),
                ('co_author1', models.CharField(default=None, max_length=400, null=True)),
                ('co_author2', models.CharField(default=None, max_length=800, null=True)),
                ('publisher', models.CharField(default=None, max_length=400)),
                ('place_of_publication', models.CharField(default=None, max_length=400)),
                ('year_of_publication', models.IntegerField(default=None)),
                ('edition_no', models.IntegerField(default=None)),
                ('staff', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='book_published', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Books Published',
            },
        ),
    ]
