# Generated by Django 2.2.6 on 2019-11-23 20:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0040_book_published_experience_abroad_ext_and_outreach_prog_invited_lectures'),
    ]

    operations = [
        migrations.RenameField(
            model_name='invited_lectures',
            old_name='instituion',
            new_name='institution',
        ),
    ]
