# Generated by Django 2.2.6 on 2019-11-23 20:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0041_auto_20191124_0154'),
    ]

    operations = [
        migrations.RenameField(
            model_name='experience_abroad',
            old_name='instituion',
            new_name='institution',
        ),
    ]
