# Generated by Django 2.2.6 on 2019-11-26 11:51

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0045_auto_20191126_1249'),
    ]

    operations = [
        migrations.AddField(
            model_name='csw',
            name='pdf',
            field=models.FileField(default=None, max_length=400, upload_to='csw', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf'])]),
        ),
    ]
