# Generated by Django 3.0 on 2019-12-06 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0048_auto_20191204_0156'),
    ]

    operations = [
        migrations.AddField(
            model_name='employment',
            name='to_date',
            field=models.DateField(default=None, null=True),
        ),
    ]
