# Generated by Django 3.0 on 2019-12-27 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0049_employment_to_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff_detail',
            name='disability',
            field=models.CharField(default=None, max_length=200),
        ),
        migrations.AddField(
            model_name='staff_detail',
            name='intercom1',
            field=models.IntegerField(default=None),
        ),
        migrations.AddField(
            model_name='staff_detail',
            name='intercom2',
            field=models.IntegerField(default=None),
        ),
        migrations.AddField(
            model_name='staff_detail',
            name='salutation',
            field=models.CharField(default=None, max_length=200),
        ),
        migrations.AlterField(
            model_name='staff_detail',
            name='aadhar',
            field=models.IntegerField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='staff_detail',
            name='official_mail',
            field=models.EmailField(default=None, help_text='A valid email address, please.', max_length=254),
        ),
        migrations.AlterField(
            model_name='staff_detail',
            name='pan',
            field=models.IntegerField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='staff_detail',
            name='res_address',
            field=models.CharField(default=None, max_length=1000),
        ),
        migrations.AlterField(
            model_name='staff_detail',
            name='website_url',
            field=models.URLField(default=None, max_length=1000, null=True),
        ),
    ]
