# Generated by Django 3.0 on 2019-12-27 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0053_auto_20191228_0139'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff_detail',
            name='disability',
            field=models.CharField(default=None, max_length=200),
        ),
    ]
