# Generated by Django 3.0 on 2019-12-27 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0054_auto_20191228_0140'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff_detail',
            name='website_url',
            field=models.URLField(blank=True, default=None, max_length=1000, null=True),
        ),
    ]
