# Generated by Django 3.0 on 2019-12-27 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0055_auto_20191228_0143'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff_detail',
            name='aadhar',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='staff_detail',
            name='caste',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='staff_detail',
            name='community',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='staff_detail',
            name='gender',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='staff_detail',
            name='pan',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='staff_detail',
            name='perm_address',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
