# Generated by Django 3.0 on 2019-12-27 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0056_auto_20191228_0146'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff_detail',
            name='perm_address',
            field=models.CharField(blank=True, default=None, max_length=1000, null=True),
        ),
    ]
