# Generated by Django 3.0 on 2019-12-27 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0057_auto_20191228_0146'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff_detail',
            name='aadhar',
            field=models.IntegerField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='staff_detail',
            name='pan',
            field=models.IntegerField(default=None, null=True),
        ),
    ]
