# Generated by Django 3.0 on 2019-12-27 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0058_auto_20191228_0149'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff_detail',
            name='aadhar',
            field=models.IntegerField(blank=True, default=None),
        ),
        migrations.AlterField(
            model_name='staff_detail',
            name='pan',
            field=models.IntegerField(blank=True, default=None),
        ),
    ]
