# Generated by Django 3.0 on 2019-12-27 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0059_auto_20191228_0151'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff_detail',
            name='aadhar',
            field=models.IntegerField(default=None),
        ),
        migrations.AlterField(
            model_name='staff_detail',
            name='pan',
            field=models.IntegerField(default=None),
        ),
    ]
