# Generated by Django 3.0 on 2019-12-27 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0064_auto_20191228_0159'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff_detail',
            name='aadhar',
            field=models.BigIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='staff_detail',
            name='pan',
            field=models.BigIntegerField(blank=True, default=0, null=True),
        ),
    ]
