# Generated by Django 3.0 on 2019-12-27 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0065_auto_20191228_0201'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff_detail',
            name='aadhar',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='staff_detail',
            name='pan',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
