# Generated by Django 3.0 on 2019-12-28 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0071_auto_20191228_0221'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff_detail',
            name='personal_mail',
            field=models.EmailField(blank=True, help_text='A valid email address, please.', max_length=254, null=True),
        ),
    ]
