# Generated by Django 3.0 on 2020-01-01 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0072_auto_20191228_1146'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='qualification',
            name='duration',
        ),
        migrations.AddField(
            model_name='qualification',
            name='durationfrom',
            field=models.IntegerField(default=None),
        ),
        migrations.AddField(
            model_name='qualification',
            name='durationto',
            field=models.IntegerField(default=None),
        ),
    ]
