# Generated by Django 3.0 on 2020-01-01 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0073_auto_20200101_1359'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qualification',
            name='durationfrom',
            field=models.CharField(default=None, max_length=10),
        ),
        migrations.AlterField(
            model_name='qualification',
            name='durationto',
            field=models.CharField(default=None, max_length=10),
        ),
    ]
