# Generated by Django 3.0 on 2020-01-01 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0074_auto_20200101_1434'),
    ]

    operations = [
        migrations.AddField(
            model_name='publication',
            name='all_auth_inorder',
            field=models.CharField(default=None, max_length=800),
        ),
        migrations.AddField(
            model_name='publication',
            name='corres_author',
            field=models.CharField(blank=True, max_length=400, null=True),
        ),
        migrations.AddField(
            model_name='publication',
            name='first_author',
            field=models.CharField(default=None, max_length=400),
        ),
        migrations.AddField(
            model_name='publication',
            name='impact_factor',
            field=models.IntegerField(default=None),
        ),
        migrations.AddField(
            model_name='publication',
            name='issue',
            field=models.IntegerField(default=None),
        ),
        migrations.AddField(
            model_name='publication',
            name='journal_name',
            field=models.CharField(default=None, max_length=800),
        ),
        migrations.AddField(
            model_name='publication',
            name='page_no',
            field=models.CharField(default=None, max_length=300),
        ),
        migrations.AddField(
            model_name='publication',
            name='publisher',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='publication',
            name='ref_journal',
            field=models.CharField(default=None, max_length=300),
        ),
        migrations.AddField(
            model_name='publication',
            name='volume',
            field=models.IntegerField(default=None),
        ),
        migrations.AlterField(
            model_name='publication',
            name='year',
            field=models.CharField(default=None, max_length=100),
        ),
    ]
