# Generated by Django 3.0 on 2020-01-03 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0075_auto_20200101_1827'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff_detail',
            name='profile_pic',
            field=models.ImageField(default=None, upload_to='images/profile'),
        ),
    ]
