# Generated by Django 3.0 on 2020-01-03 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0076_staff_detail_profile_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff_detail',
            name='profile_pic',
            field=models.ImageField(default=None, null=True, upload_to='images/profile'),
        ),
    ]
