# Generated by Django 3.0 on 2020-01-11 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0077_auto_20200104_0024'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='co_dep',
            field=models.CharField(default=None, max_length=800, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='co_inst',
            field=models.CharField(default=None, max_length=800, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='co_inves1',
            field=models.CharField(default=None, max_length=800, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='co_inves2',
            field=models.CharField(default=None, max_length=800, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='department',
            field=models.CharField(default=None, max_length=800),
        ),
        migrations.AddField(
            model_name='project',
            name='durationfrom',
            field=models.CharField(default=None, max_length=10),
        ),
        migrations.AddField(
            model_name='project',
            name='durationto',
            field=models.CharField(default=None, max_length=10),
        ),
        migrations.AddField(
            model_name='project',
            name='investigator',
            field=models.CharField(default=None, max_length=800),
        ),
        migrations.AddField(
            model_name='project',
            name='pro_abstract',
            field=models.CharField(default=None, max_length=1800, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='pro_status',
            field=models.CharField(default=None, max_length=800),
        ),
    ]
