# Generated by Django 3.0 on 2020-01-11 07:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0078_auto_20200111_1206'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='pro_status',
            new_name='p_type',
        ),
    ]
