# Generated by Django 3.0 on 2020-01-11 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0081_auto_20200111_1409'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experience_abroad',
            name='from_date',
            field=models.CharField(default=None, max_length=400),
        ),
        migrations.AlterField(
            model_name='experience_abroad',
            name='to_date',
            field=models.CharField(default=None, max_length=400),
        ),
    ]
