# Generated by Django 3.0 on 2020-01-11 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0082_auto_20200111_1411'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book_published',
            name='year_of_publication',
            field=models.CharField(default=None, max_length=400),
        ),
    ]
