# Generated by Django 3.0 on 2020-01-11 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0083_auto_20200111_1420'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book_published',
            name='co_author1',
            field=models.CharField(blank=True, max_length=400, null=True),
        ),
        migrations.AlterField(
            model_name='book_published',
            name='co_author2',
            field=models.CharField(blank=True, max_length=400, null=True),
        ),
    ]
