# Generated by Django 3.0 on 2020-01-14 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0085_auto_20200111_1431'),
    ]

    operations = [
        migrations.AlterField(
            model_name='area_of_spec_and_mem',
            name='area_name',
            field=models.CharField(blank=True, default=None, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='area_of_spec_and_mem',
            name='mem',
            field=models.CharField(blank=True, default=None, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='area_of_spec_and_mem',
            name='spec_mem_type',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='qualification',
            name='branch',
            field=models.CharField(blank=True, default=None, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='qualification',
            name='class_obtained',
            field=models.CharField(blank=True, default=None, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='qualification',
            name='degree',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='qualification',
            name='degree_type',
            field=models.CharField(blank=True, default=None, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='qualification',
            name='department',
            field=models.CharField(blank=True, default=None, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='qualification',
            name='durationfrom',
            field=models.CharField(blank=True, default=None, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='qualification',
            name='durationto',
            field=models.CharField(blank=True, default=None, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='qualification',
            name='faculty',
            field=models.CharField(blank=True, default=None, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='qualification',
            name='institution',
            field=models.CharField(blank=True, max_length=400, null=True),
        ),
        migrations.AlterField(
            model_name='qualification',
            name='level',
            field=models.CharField(blank=True, default=None, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='qualification',
            name='research_area',
            field=models.CharField(blank=True, default=None, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='qualification',
            name='title_of_thesis',
            field=models.CharField(blank=True, default=None, max_length=700, null=True),
        ),
        migrations.AlterField(
            model_name='qualification',
            name='university',
            field=models.CharField(blank=True, max_length=400, null=True),
        ),
        migrations.AlterField(
            model_name='qualification',
            name='viva',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='staff_detail',
            name='aadhar',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='staff_detail',
            name='disability',
            field=models.CharField(blank=True, default=None, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='staff_detail',
            name='dob',
            field=models.DateField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='staff_detail',
            name='fath_hus_name',
            field=models.CharField(blank=True, default=None, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='staff_detail',
            name='intercom1',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='staff_detail',
            name='intercom2',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='staff_detail',
            name='mobile_no',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='staff_detail',
            name='name',
            field=models.CharField(blank=True, default=None, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='staff_detail',
            name='official_mail',
            field=models.EmailField(blank=True, default=None, help_text='A valid email address, please.', max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='staff_detail',
            name='pan',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='staff_detail',
            name='res_address',
            field=models.CharField(blank=True, default=None, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='staff_detail',
            name='residence_ph_no',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='staff_detail',
            name='salutation',
            field=models.CharField(blank=True, default=None, max_length=200, null=True),
        ),
    ]
