# Generated by Django 3.0 on 2020-01-14 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0089_auto_20200114_2116'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publication',
            name='impact_factor',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
    ]
