# Generated by Django 3.0 on 2020-01-15 07:27

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0091_auto_20200114_2233'),
    ]

    operations = [
        migrations.AddField(
            model_name='csw',
            name='durationfrom',
            field=models.DateField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='csw',
            name='durationto',
            field=models.DateField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='csw',
            name='institution',
            field=models.CharField(blank=True, default=None, max_length=400, null=True),
        ),
        migrations.AlterField(
            model_name='csw',
            name='country',
            field=models.CharField(blank=True, default=None, max_length=400, null=True),
        ),
        migrations.AlterField(
            model_name='csw',
            name='csw_type',
            field=models.CharField(blank=True, max_length=400, null=True),
        ),
        migrations.AlterField(
            model_name='csw',
            name='level',
            field=models.CharField(blank=True, default=None, max_length=400, null=True),
        ),
        migrations.AlterField(
            model_name='csw',
            name='pdf',
            field=models.FileField(default=None, max_length=400, null=True, upload_to='csw', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf'])]),
        ),
        migrations.AlterField(
            model_name='csw',
            name='title',
            field=models.CharField(blank=True, default=None, max_length=800, null=True),
        ),
        migrations.AlterField(
            model_name='csw',
            name='type_name',
            field=models.CharField(blank=True, default=None, max_length=400, null=True),
        ),
    ]
