# Generated by Django 3.0 on 2020-01-15 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0092_auto_20200115_1257'),
    ]

    operations = [
        migrations.AddField(
            model_name='csw',
            name='role',
            field=models.CharField(blank=True, default=None, max_length=400, null=True),
        ),
    ]
