# Generated by Django 3.0 on 2020-01-15 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0093_csw_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='csw',
            name='all_auth',
            field=models.CharField(blank=True, max_length=400, null=True),
        ),
        migrations.AddField(
            model_name='csw',
            name='is_publi',
            field=models.CharField(blank=True, max_length=400, null=True),
        ),
        migrations.AddField(
            model_name='csw',
            name='nature_of_pres',
            field=models.CharField(blank=True, max_length=400, null=True),
        ),
        migrations.AddField(
            model_name='csw',
            name='paper_title',
            field=models.CharField(blank=True, max_length=400, null=True),
        ),
        migrations.AddField(
            model_name='csw',
            name='pres_by',
            field=models.CharField(blank=True, max_length=400, null=True),
        ),
    ]
