# Generated by Django 3.0 on 2020-01-15 09:54

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0094_auto_20200115_1334'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='amt',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='department',
            field=models.CharField(blank=True, default=None, max_length=800, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='durationfrom',
            field=models.CharField(blank=True, default=None, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='durationto',
            field=models.CharField(blank=True, default=None, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='funding_agent',
            field=models.CharField(blank=True, default=None, max_length=400, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='investigator',
            field=models.CharField(blank=True, default=None, max_length=800, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='p_type',
            field=models.CharField(blank=True, default=None, max_length=800, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='pdf',
            field=models.FileField(default=None, max_length=400, null=True, upload_to='project', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf'])]),
        ),
        migrations.AlterField(
            model_name='project',
            name='pro_title',
            field=models.CharField(blank=True, default=None, max_length=800, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='pro_type',
            field=models.CharField(blank=True, default=None, max_length=800, null=True),
        ),
    ]
