# Generated by Django 3.0 on 2020-01-15 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0095_auto_20200115_1524'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invited_lectures',
            name='date',
            field=models.CharField(blank=True, default=None, max_length=400, null=True),
        ),
        migrations.AlterField(
            model_name='invited_lectures',
            name='institution',
            field=models.CharField(blank=True, default=None, max_length=800, null=True),
        ),
        migrations.AlterField(
            model_name='invited_lectures',
            name='level',
            field=models.CharField(blank=True, default=None, max_length=400, null=True),
        ),
        migrations.AlterField(
            model_name='invited_lectures',
            name='place',
            field=models.CharField(blank=True, default=None, max_length=400, null=True),
        ),
        migrations.AlterField(
            model_name='invited_lectures',
            name='programme',
            field=models.CharField(blank=True, default=None, max_length=400, null=True),
        ),
        migrations.AlterField(
            model_name='invited_lectures',
            name='topic',
            field=models.CharField(blank=True, default=None, max_length=400, null=True),
        ),
    ]
