# Generated by Django 3.0 on 2020-01-16 07:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('staff', '0098_auto_20200115_1857'),
    ]

    operations = [
        migrations.CreateModel(
            name='achievements',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, default=None, max_length=400, null=True)),
                ('institution', models.CharField(blank=True, default=None, max_length=400, null=True)),
                ('country', models.CharField(blank=True, default=None, max_length=400, null=True)),
                ('year', models.CharField(blank=True, default=None, max_length=800, null=True)),
                ('details', models.IntegerField(blank=True, default=None, null=True)),
                ('level', models.CharField(blank=True, default=None, max_length=400, null=True)),
                ('body', models.CharField(blank=True, default=None, max_length=400, null=True)),
                ('capacity', models.CharField(blank=True, default=None, max_length=400, null=True)),
                ('from_date', models.CharField(blank=True, default=None, max_length=400, null=True)),
                ('to_date', models.CharField(blank=True, default=None, max_length=400, null=True)),
                ('patent_no', models.CharField(blank=True, default=None, max_length=400, null=True)),
                ('date', models.CharField(blank=True, default=None, max_length=400, null=True)),
                ('file_no', models.CharField(blank=True, default=None, max_length=400, null=True)),
                ('ach_type', models.CharField(blank=True, default=None, max_length=400, null=True)),
                ('staff', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='achievements', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Extension and Outreach Programmes',
            },
        ),
    ]
