# Generated by Django 3.0 on 2020-01-16 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0099_achievements'),
    ]

    operations = [
        migrations.AlterField(
            model_name='achievements',
            name='details',
            field=models.CharField(blank=True, default=None, max_length=400, null=True),
        ),
    ]
