# Generated by Django 3.0 on 2020-01-16 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0100_auto_20200116_1410'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='achievements',
            options={'verbose_name_plural': 'Achievements'},
        ),
        migrations.AlterField(
            model_name='achievements',
            name='details',
            field=models.CharField(blank=True, default=None, max_length=800, null=True),
        ),
    ]
