# Generated by Django 3.0 on 2020-01-16 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0102_logindetails'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logindetails',
            name='user_type',
            field=models.CharField(blank=True, default='new', max_length=200, null=True),
        ),
    ]
