# Generated by Django 3.0 on 2020-01-18 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0104_auto_20200118_1557'),
    ]

    operations = [
        migrations.AddField(
            model_name='employment',
            name='scale_of_pay',
            field=models.CharField(blank=True, default=None, max_length=400, null=True),
        ),
    ]
