# Generated by Django 3.0 on 2020-01-18 18:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('staff', '0105_employment_scale_of_pay'),
    ]

    operations = [
        migrations.CreateModel(
            name='research',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reg_no', models.CharField(blank=True, default=None, max_length=400, null=True)),
                ('name_of_scholar', models.CharField(blank=True, default=None, max_length=400, null=True)),
                ('title', models.CharField(blank=True, default=None, max_length=400, null=True)),
                ('status', models.CharField(blank=True, default=None, max_length=800, null=True)),
                ('capacity', models.CharField(blank=True, default=None, max_length=800, null=True)),
                ('phd_s_g', models.CharField(blank=True, default=None, max_length=400, null=True)),
                ('phd_s_o', models.CharField(blank=True, default=None, max_length=400, null=True)),
                ('phd_js_g', models.CharField(blank=True, default=None, max_length=400, null=True)),
                ('phd_js_o', models.CharField(blank=True, default=None, max_length=400, null=True)),
                ('ms_s_g', models.CharField(blank=True, default=None, max_length=400, null=True)),
                ('ms_s_o', models.CharField(blank=True, default=None, max_length=400, null=True)),
                ('ms_js_g', models.CharField(blank=True, default=None, max_length=400, null=True)),
                ('ms_js_o', models.CharField(blank=True, default=None, max_length=400, null=True)),
                ('me_s_g', models.CharField(blank=True, default=None, max_length=400, null=True)),
                ('me_s_o', models.CharField(blank=True, default=None, max_length=400, null=True)),
                ('msc_s_g', models.CharField(blank=True, default=None, max_length=400, null=True)),
                ('msc_s_o', models.CharField(blank=True, default=None, max_length=400, null=True)),
                ('staff', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='research', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Research',
            },
        ),
    ]
