# Generated by Django 3.0 on 2020-01-18 19:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('staff', '0106_research'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='research',
            name='me_s_g',
        ),
        migrations.RemoveField(
            model_name='research',
            name='me_s_o',
        ),
        migrations.RemoveField(
            model_name='research',
            name='ms_js_g',
        ),
        migrations.RemoveField(
            model_name='research',
            name='ms_js_o',
        ),
        migrations.RemoveField(
            model_name='research',
            name='ms_s_g',
        ),
        migrations.RemoveField(
            model_name='research',
            name='ms_s_o',
        ),
        migrations.RemoveField(
            model_name='research',
            name='msc_s_g',
        ),
        migrations.RemoveField(
            model_name='research',
            name='msc_s_o',
        ),
        migrations.RemoveField(
            model_name='research',
            name='phd_js_g',
        ),
        migrations.RemoveField(
            model_name='research',
            name='phd_js_o',
        ),
        migrations.RemoveField(
            model_name='research',
            name='phd_s_g',
        ),
        migrations.RemoveField(
            model_name='research',
            name='phd_s_o',
        ),
        migrations.CreateModel(
            name='research_table',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phd_reg_no', models.CharField(blank=True, default=None, max_length=400, null=True)),
                ('phd_s_g', models.CharField(blank=True, default=None, max_length=400, null=True)),
                ('phd_s_o', models.CharField(blank=True, default=None, max_length=400, null=True)),
                ('phd_js_g', models.CharField(blank=True, default=None, max_length=400, null=True)),
                ('phd_js_o', models.CharField(blank=True, default=None, max_length=400, null=True)),
                ('ms_s_g', models.CharField(blank=True, default=None, max_length=400, null=True)),
                ('ms_s_o', models.CharField(blank=True, default=None, max_length=400, null=True)),
                ('ms_js_g', models.CharField(blank=True, default=None, max_length=400, null=True)),
                ('ms_js_o', models.CharField(blank=True, default=None, max_length=400, null=True)),
                ('me_s_g', models.CharField(blank=True, default=None, max_length=400, null=True)),
                ('me_s_o', models.CharField(blank=True, default=None, max_length=400, null=True)),
                ('msc_s_g', models.CharField(blank=True, default=None, max_length=400, null=True)),
                ('msc_s_o', models.CharField(blank=True, default=None, max_length=400, null=True)),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='research_table', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Research Table',
            },
        ),
    ]
