# Generated by Django 3.0 on 2020-01-18 19:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0107_auto_20200119_0032'),
    ]

    operations = [
        migrations.RenameField(
            model_name='research_table',
            old_name='user',
            new_name='staff',
        ),
    ]
