# Generated by Django 3.0 on 2020-03-14 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0109_auto_20200119_1910'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publication',
            name='year',
            field=models.DateField(blank=True, null=True),
        ),
    ]
