export const USER_LOADING = "USER_LOADING";
export const USER_LOADED = "USER_LOADED";
export const AUTH_ERROR = "AUTH_ERROR";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAIL = "LOGIN_FAIL";
export const LOGOUT_SUCCESS = "LOGOUT_SUCCESS";
export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const REGISTER_FAIL = "REGISTER_FAIL";

export const PASSWORD_CHANGED = "PASSWORD_CHANGED";
export const PASSWORD_CHANGE_ERROR = "PASSWORD_CHANGE_ERROR";

export const GET_STAFFINFO = "GET_STAFFINFO";
export const ADD_STAFFINFO = "ADD_STAFFINFO";
export const EDIT_STAFFINFO = "EDIT_STAFFINFO";
export const DELETE_STAFFINFO = "DELETE_STAFFINFO";
export const GET_STAFFINFO_BY_ID = "GET_STAFFINFO_BY_ID";

export const GET_QUALIFICATION = "GET_QUALIFICATION";
export const ADD_QUALIFICATION = "ADD_QUALIFICATION";
export const EDIT_QUALIFICATION = "EDIT_QUALIFICATION";
export const DELETE_QUALIFICATION = "DELETE_QUALIFICATION";
export const GET_QUALIFICATION_BY_ID = "GET_QUALIFICATION_BY_ID";

export const GET_SPECIALIZATION = "GET_SPECIALIZATION";
export const ADD_SPECIALIZATION = "ADD_SPECIALIZATION";
export const EDIT_SPECIALIZATION = "EDIT_SPECIALIZATION";
export const DELETE_SPECIALIZATION = "DELETE_SPECIALIZATION";
export const GET_SPECIALIZATION_BY_ID = "GET_SPECIALIZATION_BY_ID";

export const GET_EMPLOYMENT = "GET_EMPLOYMENT";
export const ADD_EMPLOYMENT = "ADD_EMPLOYMENT";
export const EDIT_EMPLOYMENT = "EDIT_EMPLOYMENT";
export const DELETE_EMPLOYMENT = "DELETE_EMPLOYMENT";
export const GET_EMPLOYMENT_BY_ID = "GET_EMPLOYMENT_BY_ID";

export const GET_PUBLICATION = "GET_PUBLICATION";
export const ADD_PUBLICATION = "ADD_PUBLICATION";
export const EDIT_PUBLICATION = "EDIT_PUBLICATION";
export const DELETE_PUBLICATION = "DELETE_PUBLICATION";
export const GET_PUBLICATION_BY_ID = "GET_PUBLICATION_BY_ID";

export const GET_CSW = "GET_CSW";
export const ADD_CSW = "ADD_CSW";
export const EDIT_CSW = "EDIT_CSW";
export const DELETE_CSW = "DELETE_CSW";
export const GET_CSW_BY_ID = "GET_CSW_BY_ID";

export const GET_PROJECT = "GET_PROJECT";
export const ADD_PROJECT = "ADD_PROJECT";
export const EDIT_PROJECT = "EDIT_PROJECT";
export const DELETE_PROJECT = "DELETE_PROJECT";
export const GET_PROJECT_BY_ID = "GET_PROJECT_BY_ID";

export const GET_INVITED_LECTURES = "GET_INVITED_LECTURES";
export const ADD_INVITED_LECTURES = "ADD_INVITED_LECTURES";

export const GET_EXPERIENCE_ABROAD = "GET_EXPERIENCE_ABROAD";
export const ADD_EXPERIENCE_ABROAD = "ADD_EXPERIENCE_ABROAD";

export const GET_BOOK_PUBLISHED = "GET_BOOK_PUBLISHED";
export const ADD_BOOK_PUBLISHED = "ADD_BOOK_PUBLISHED";

export const GET_EAO_PROGRAMME = "GET_EAO_PROGRAMME";
export const ADD_EAO_PROGRAMME = "ADD_EAO_PROGRAMME";

