export const USER_LOADING = "USER_LOADING";
export const USER_LOADED = "USER_LOADED";
export const AUTH_ERROR = "AUTH_ERROR";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAIL = "LOGIN_FAIL";
export const LOGOUT_SUCCESS = "LOGOUT_SUCCESS";
export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const REGISTER_FAIL = "REGISTER_FAIL";

export const GET_STAFFINFO = "GET_STAFFINFO";
export const ADD_STAFFINFO = "ADD_STAFFINFO";

export const GET_QUALIFICATION = "GET_QUALIFICATION";
export const ADD_QUALIFICATION = "ADD_QUALIFICATION";

export const GET_SPECIALIZATION = "GET_SPECIALIZATION";
export const ADD_SPECIALIZATION = "ADD_SPECIALIZATION";

export const GET_EMPLOYMENT = "GET_EMPLOYMENT";
export const ADD_EMPLOYMENT = "ADD_EMPLOYMENT";

